var Ardublockly = Ardublockly || {};
Ardublockly.LOCALISED_TEXT = {
  translationLanguage: "Français",
  title: "Ardublockly",
  blocks: "Blocs",
  /* Menu */
  open: "Ouvrir",
  save: "Enregistrer",
  deleteAll: "Abandonner Tous",
  settings: "",
  documentation: "Documentation",
  reportBug: "",
  examples: "Exemples",
  /* Settings */
  compilerLocation: "",
  compilerLocationDefault: "",
  sketchFolder: "",
  sketchFolderDefault: "",
  arduinoBoard: "Carte Arduino",
  arduinoBoardDefault: "Carte Arduino inconnu",
  comPort: "Port Série",
  comPortDefault: "COM3",
  defaultIdeButton: "",
  defaultIdeButtonDefault: "",
  language: "Langue",
  languageDefault: "Langue inconnu",
  sketchName: "Nom de Sketch",
  /* Arduino console output */
  arduinoOpMainTitle: "Console Arduno IDE",
  arduinoOpWaiting: "Chargement de la reponse Arduino IDE",
  arduinoOpUploadedTitle: "Téléversement terminé",
  arduinoOpVerifiedTitle: "Compilation terminé",
  arduinoOpOpenedTitle: "Sketch ouvert dans l'IDE",
  arduinoOpOpenedBody: "Le Sketch est normalement ouvert dans l'IDE",
  arduinoOpErrorUpVerTitle: "La compilation ou le téléversement à échoué",
  arduinoOpErrorSketchTitle: "",
  arduinoOpErrorFlagTitle: "",
  arduinoOpErrorFlagPrefTitle: "",
  arduinoOpErrorIdeDirTitle: "",
  arduinoOpErrorIdeDirBody: "",
  arduinoOpErrorIdeOptionTitle: "",
  arduinoOpErrorIdeOptionBody: "L'option de démarage de l'IDE n'a pas encore été défini.<br>" +
                               "Veuillez selectionner une option dans les paramètres.",
  arduinoOpErrorIdePortTitle: "Aucun port série disponible",
  arduinoOpErrorIdePortBody: "Erreur : Le port série ne réponds pas",
  arduinoOpErrorIdeBoardTitle: "",
  arduinoOpErrorIdeBoardBody: "",
  /* Modals */
  noServerTitle: "",
  noServerTitleBody: "",
  noServerNoLangBody: "",
  addBlocksTitle: "",
  /* Alerts */
  loadNewBlocksTitle: "",
  loadNewBlocksBody: "",
  discardBlocksTitle: "",
  discardBlocksBody: "",
  invalidXmlTitle: "",
  invalidXmlBody: "",
  /* Tooltips */
  uploadingSketch: "Televersement...",
  uploadSketch: "Televerser",
  verifyingSketch: "Verification...",
  verifySketch: "Verifier",
  openingSketch: "Ouverture...",
  openSketch: "Ouvrir dans l'IDE",
  notImplemented: "",
  /* Prompts */
  ok: "OK",
  okay: "Okay",
  cancel: "Annuler",
  return: "Retour",
  /* Cards */
  arduinoSourceCode: "",
  blocksXml: "Blocs XML",
  /* Toolbox Categories*/
  catLogic: "Logique",
  catLoops: "Boucles",
  catMath: "Math",
  catText: "Texte",
  catVariables: "Variables",
  catFunctions: "Fonctions",
  catInputOutput: "Entree/Sortie",
  catTime: "Temps",
  catAudio: "Audio",
  catMotors: "Moteurs",
  catComms: "Comms",
};
